version: "3.8"
services:
  app:
    container_name: word-study-game-nextjs-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/vscode/.ssh
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: host